INSERT INTO grupos (nome,conta_id) VALUES ('Dívidas',1);
INSERT INTO grupos (nome,conta_id) VALUES ('Moradia',1);
INSERT INTO grupos (nome,conta_id) VALUES ('Alimentação',1);
INSERT INTO grupos (nome,conta_id) VALUES ('Saúde',1);
INSERT INTO grupos (nome,conta_id) VALUES ('Educação',1);
INSERT INTO grupos (nome,conta_id) VALUES ('Vestuário',1);
INSERT INTO grupos (nome,conta_id) VALUES ('Transporte',1);
INSERT INTO grupos (nome,conta_id) VALUES ('Lazer',1);
INSERT INTO grupos (nome,conta_id) VALUES ('Despesas Pessoais',1);
INSERT INTO grupos (nome,conta_id) VALUES ('Despesas Financeiras',1);
INSERT INTO grupos (nome,conta_id) VALUES ('Outras',1);
