INSERT INTO subgrupos (grupo_id,nome,id_tipo) VALUES ((SELECT id FROM grupos WHERE nome = 'Dívidas' and conta_id = 1),'Crediário',(SELECT id FROM tipo_subgrupo WHERE nome = 'fixo'));
INSERT INTO subgrupos (grupo_id,nome,id_tipo) VALUES ((SELECT id FROM grupos WHERE nome = 'Dívidas' and conta_id = 1),'Cartão de crédito',(SELECT id FROM tipo_subgrupo WHERE nome = 'variável'));
INSERT INTO subgrupos (grupo_id,nome,id_tipo) VALUES ((SELECT id FROM grupos WHERE nome = 'Dívidas' and conta_id = 1),'Cheque especial',(SELECT id FROM tipo_subgrupo WHERE nome = 'variável'));
INSERT INTO subgrupos (grupo_id,nome,id_tipo) VALUES ((SELECT id FROM grupos WHERE nome = 'Dívidas' and conta_id = 1),'Outro',(SELECT id FROM tipo_subgrupo WHERE nome = 'variável'));
INSERT INTO subgrupos (grupo_id,nome,id_tipo) VALUES ((SELECT id FROM grupos WHERE nome = 'Moradia' and conta_id = 1),'Aluguel',(SELECT id FROM tipo_subgrupo WHERE nome = 'fixo'));
INSERT INTO subgrupos (grupo_id,nome,id_tipo) VALUES ((SELECT id FROM grupos WHERE nome = 'Moradia' and conta_id = 1),'Condomínio',(SELECT id FROM tipo_subgrupo WHERE nome = 'fixo'));
INSERT INTO subgrupos (grupo_id,nome,id_tipo) VALUES ((SELECT id FROM grupos WHERE nome = 'Moradia' and conta_id = 1),'IPTU',(SELECT id FROM tipo_subgrupo WHERE nome = 'fixo'));
INSERT INTO subgrupos (grupo_id,nome,id_tipo) VALUES ((SELECT id FROM grupos WHERE nome = 'Moradia' and conta_id = 1),'Empregado(a)',(SELECT id FROM tipo_subgrupo WHERE nome = 'fixo'));
INSERT INTO subgrupos (grupo_id,nome,id_tipo) VALUES ((SELECT id FROM grupos WHERE nome = 'Moradia' and conta_id = 1),'Água',(SELECT id FROM tipo_subgrupo WHERE nome = 'variável'));
INSERT INTO subgrupos (grupo_id,nome,id_tipo) VALUES ((SELECT id FROM grupos WHERE nome = 'Moradia' and conta_id = 1),'Luz',(SELECT id FROM tipo_subgrupo WHERE nome = 'variável'));
INSERT INTO subgrupos (grupo_id,nome,id_tipo) VALUES ((SELECT id FROM grupos WHERE nome = 'Moradia' and conta_id = 1),'Gás',(SELECT id FROM tipo_subgrupo WHERE nome = 'variável'));
INSERT INTO subgrupos (grupo_id,nome,id_tipo) VALUES ((SELECT id FROM grupos WHERE nome = 'Moradia' and conta_id = 1),'Telefone fixo',(SELECT id FROM tipo_subgrupo WHERE nome = 'variável'));
INSERT INTO subgrupos (grupo_id,nome,id_tipo) VALUES ((SELECT id FROM grupos WHERE nome = 'Moradia' and conta_id = 1),'Telefone celular',(SELECT id FROM tipo_subgrupo WHERE nome = 'variável'));
INSERT INTO subgrupos (grupo_id,nome,id_tipo) VALUES ((SELECT id FROM grupos WHERE nome = 'Moradia' and conta_id = 1),'TV a cabo',(SELECT id FROM tipo_subgrupo WHERE nome = 'fixo'));
INSERT INTO subgrupos (grupo_id,nome,id_tipo) VALUES ((SELECT id FROM grupos WHERE nome = 'Moradia' and conta_id = 1),'Internet',(SELECT id FROM tipo_subgrupo WHERE nome = 'variável'));
INSERT INTO subgrupos (grupo_id,nome,id_tipo) VALUES ((SELECT id FROM grupos WHERE nome = 'Moradia' and conta_id = 1),'Móveis/Utensílios',(SELECT id FROM tipo_subgrupo WHERE nome = 'eventual'));
INSERT INTO subgrupos (grupo_id,nome,id_tipo) VALUES ((SELECT id FROM grupos WHERE nome = 'Moradia' and conta_id = 1),'Consertos',(SELECT id FROM tipo_subgrupo WHERE nome = 'eventual'));
INSERT INTO subgrupos (grupo_id,nome,id_tipo) VALUES ((SELECT id FROM grupos WHERE nome = 'Alimentação' and conta_id = 1),'Supermercado',(SELECT id FROM tipo_subgrupo WHERE nome = 'variável'));
INSERT INTO subgrupos (grupo_id,nome,id_tipo) VALUES ((SELECT id FROM grupos WHERE nome = 'Alimentação' and conta_id = 1),'Açougue',(SELECT id FROM tipo_subgrupo WHERE nome = 'variável'));
INSERT INTO subgrupos (grupo_id,nome,id_tipo) VALUES ((SELECT id FROM grupos WHERE nome = 'Alimentação' and conta_id = 1),'Feira',(SELECT id FROM tipo_subgrupo WHERE nome = 'variável'));
INSERT INTO subgrupos (grupo_id,nome,id_tipo) VALUES ((SELECT id FROM grupos WHERE nome = 'Alimentação' and conta_id = 1),'Padaria',(SELECT id FROM tipo_subgrupo WHERE nome = 'variável'));
INSERT INTO subgrupos (grupo_id,nome,id_tipo) VALUES ((SELECT id FROM grupos WHERE nome = 'Alimentação' and conta_id = 1),'Restaurante',(SELECT id FROM tipo_subgrupo WHERE nome = 'variável'));
INSERT INTO subgrupos (grupo_id,nome,id_tipo) VALUES ((SELECT id FROM grupos WHERE nome = 'Saúde' and conta_id = 1),'Convênio',(SELECT id FROM tipo_subgrupo WHERE nome = 'fixo'));
INSERT INTO subgrupos (grupo_id,nome,id_tipo) VALUES ((SELECT id FROM grupos WHERE nome = 'Saúde' and conta_id = 1),'Médico',(SELECT id FROM tipo_subgrupo WHERE nome = 'eventual'));
INSERT INTO subgrupos (grupo_id,nome,id_tipo) VALUES ((SELECT id FROM grupos WHERE nome = 'Saúde' and conta_id = 1),'Dentista',(SELECT id FROM tipo_subgrupo WHERE nome = 'eventual'));
INSERT INTO subgrupos (grupo_id,nome,id_tipo) VALUES ((SELECT id FROM grupos WHERE nome = 'Saúde' and conta_id = 1),'Farmácia',(SELECT id FROM tipo_subgrupo WHERE nome = 'eventual'));
INSERT INTO subgrupos (grupo_id,nome,id_tipo) VALUES ((SELECT id FROM grupos WHERE nome = 'Educação' and conta_id = 1),'Escola',(SELECT id FROM tipo_subgrupo WHERE nome = 'fixo'));
INSERT INTO subgrupos (grupo_id,nome,id_tipo) VALUES ((SELECT id FROM grupos WHERE nome = 'Educação' and conta_id = 1),'Material',(SELECT id FROM tipo_subgrupo WHERE nome = 'eventual'));
INSERT INTO subgrupos (grupo_id,nome,id_tipo) VALUES ((SELECT id FROM grupos WHERE nome = 'Educação' and conta_id = 1),'Uniforme',(SELECT id FROM tipo_subgrupo WHERE nome = 'eventual'));
INSERT INTO subgrupos (grupo_id,nome,id_tipo) VALUES ((SELECT id FROM grupos WHERE nome = 'Educação' and conta_id = 1),'Cursos extras',(SELECT id FROM tipo_subgrupo WHERE nome = 'fixo'));
INSERT INTO subgrupos (grupo_id,nome,id_tipo) VALUES ((SELECT id FROM grupos WHERE nome = 'Vestuário' and conta_id = 1),'Roupas',(SELECT id FROM tipo_subgrupo WHERE nome = 'variável'));
INSERT INTO subgrupos (grupo_id,nome,id_tipo) VALUES ((SELECT id FROM grupos WHERE nome = 'Vestuário' and conta_id = 1),'Calçados',(SELECT id FROM tipo_subgrupo WHERE nome = 'variável'));
INSERT INTO subgrupos (grupo_id,nome,id_tipo) VALUES ((SELECT id FROM grupos WHERE nome = 'Vestuário' and conta_id = 1),'Acessórios',(SELECT id FROM tipo_subgrupo WHERE nome = 'variável'));
INSERT INTO subgrupos (grupo_id,nome,id_tipo) VALUES ((SELECT id FROM grupos WHERE nome = 'Transporte' and conta_id = 1),'Ônibus',(SELECT id FROM tipo_subgrupo WHERE nome = 'fixo'));
INSERT INTO subgrupos (grupo_id,nome,id_tipo) VALUES ((SELECT id FROM grupos WHERE nome = 'Transporte' and conta_id = 1),'Metro',(SELECT id FROM tipo_subgrupo WHERE nome = 'fixo'));
INSERT INTO subgrupos (grupo_id,nome,id_tipo) VALUES ((SELECT id FROM grupos WHERE nome = 'Transporte' and conta_id = 1),'Táxi',(SELECT id FROM tipo_subgrupo WHERE nome = 'eventual'));
INSERT INTO subgrupos (grupo_id,nome,id_tipo) VALUES ((SELECT id FROM grupos WHERE nome = 'Transporte' and conta_id = 1),'IPVA',(SELECT id FROM tipo_subgrupo WHERE nome = 'fixo'));
INSERT INTO subgrupos (grupo_id,nome,id_tipo) VALUES ((SELECT id FROM grupos WHERE nome = 'Transporte' and conta_id = 1),'Prestação carro/moto',(SELECT id FROM tipo_subgrupo WHERE nome = 'fixo'));
INSERT INTO subgrupos (grupo_id,nome,id_tipo) VALUES ((SELECT id FROM grupos WHERE nome = 'Transporte' and conta_id = 1),'Seguro',(SELECT id FROM tipo_subgrupo WHERE nome = 'fixo'));
INSERT INTO subgrupos (grupo_id,nome,id_tipo) VALUES ((SELECT id FROM grupos WHERE nome = 'Transporte' and conta_id = 1),'Licenciamento',(SELECT id FROM tipo_subgrupo WHERE nome = 'fixo'));
INSERT INTO subgrupos (grupo_id,nome,id_tipo) VALUES ((SELECT id FROM grupos WHERE nome = 'Transporte' and conta_id = 1),'Combustível',(SELECT id FROM tipo_subgrupo WHERE nome = 'variável'));
INSERT INTO subgrupos (grupo_id,nome,id_tipo) VALUES ((SELECT id FROM grupos WHERE nome = 'Transporte' and conta_id = 1),'Manutenção',(SELECT id FROM tipo_subgrupo WHERE nome = 'eventual'));
INSERT INTO subgrupos (grupo_id,nome,id_tipo) VALUES ((SELECT id FROM grupos WHERE nome = 'Transporte' and conta_id = 1),'Multas de trânsito',(SELECT id FROM tipo_subgrupo WHERE nome = 'eventual'));
INSERT INTO subgrupos (grupo_id,nome,id_tipo) VALUES ((SELECT id FROM grupos WHERE nome = 'Transporte' and conta_id = 1),'Estacionamento',(SELECT id FROM tipo_subgrupo WHERE nome = 'eventual'));
INSERT INTO subgrupos (grupo_id,nome,id_tipo) VALUES ((SELECT id FROM grupos WHERE nome = 'Lazer' and conta_id = 1),'Livros/revistas',(SELECT id FROM tipo_subgrupo WHERE nome = 'variável'));
INSERT INTO subgrupos (grupo_id,nome,id_tipo) VALUES ((SELECT id FROM grupos WHERE nome = 'Lazer' and conta_id = 1),'Cinema/teatro',(SELECT id FROM tipo_subgrupo WHERE nome = 'variável'));
INSERT INTO subgrupos (grupo_id,nome,id_tipo) VALUES ((SELECT id FROM grupos WHERE nome = 'Lazer' and conta_id = 1),'Bares',(SELECT id FROM tipo_subgrupo WHERE nome = 'eventual'));
INSERT INTO subgrupos (grupo_id,nome,id_tipo) VALUES ((SELECT id FROM grupos WHERE nome = 'Lazer' and conta_id = 1),'Viagem/Passeio',(SELECT id FROM tipo_subgrupo WHERE nome = 'variável'));
INSERT INTO subgrupos (grupo_id,nome,id_tipo) VALUES ((SELECT id FROM grupos WHERE nome = 'Lazer' and conta_id = 1),'Presentes',(SELECT id FROM tipo_subgrupo WHERE nome = 'variável'));
INSERT INTO subgrupos (grupo_id,nome,id_tipo) VALUES ((SELECT id FROM grupos WHERE nome = 'Despesas Pessoais' and conta_id = 1),'Academia',(SELECT id FROM tipo_subgrupo WHERE nome = 'fixo'));
INSERT INTO subgrupos (grupo_id,nome,id_tipo) VALUES ((SELECT id FROM grupos WHERE nome = 'Despesas Pessoais' and conta_id = 1),'Seguro de vida',(SELECT id FROM tipo_subgrupo WHERE nome = 'fixo'));
INSERT INTO subgrupos (grupo_id,nome,id_tipo) VALUES ((SELECT id FROM grupos WHERE nome = 'Despesas Pessoais' and conta_id = 1),'Cabeleireiro',(SELECT id FROM tipo_subgrupo WHERE nome = 'variável'));
INSERT INTO subgrupos (grupo_id,nome,id_tipo) VALUES ((SELECT id FROM grupos WHERE nome = 'Despesas Pessoais' and conta_id = 1),'Manicure',(SELECT id FROM tipo_subgrupo WHERE nome = 'variável'));
INSERT INTO subgrupos (grupo_id,nome,id_tipo) VALUES ((SELECT id FROM grupos WHERE nome = 'Despesas Pessoais' and conta_id = 1),'Produto de beleza',(SELECT id FROM tipo_subgrupo WHERE nome = 'variável'));
INSERT INTO subgrupos (grupo_id,nome,id_tipo) VALUES ((SELECT id FROM grupos WHERE nome = 'Despesas Financeiras' and conta_id = 1),'Juros',(SELECT id FROM tipo_subgrupo WHERE nome = 'variável'));
INSERT INTO subgrupos (grupo_id,nome,id_tipo) VALUES ((SELECT id FROM grupos WHERE nome = 'Despesas Financeiras' and conta_id = 1),'Multas',(SELECT id FROM tipo_subgrupo WHERE nome = 'eventual'));
INSERT INTO subgrupos (grupo_id,nome,id_tipo) VALUES ((SELECT id FROM grupos WHERE nome = 'Despesas Financeiras' and conta_id = 1),'Tarifas bancárias',(SELECT id FROM tipo_subgrupo WHERE nome = 'variável'));
INSERT INTO subgrupos (grupo_id,nome,id_tipo) VALUES ((SELECT id FROM grupos WHERE nome = 'Despesas Financeiras' and conta_id = 1),'Anuidades',(SELECT id FROM tipo_subgrupo WHERE nome = 'variável'));
INSERT INTO subgrupos (grupo_id,nome,id_tipo) VALUES ((SELECT id FROM grupos WHERE nome = 'Outras' and conta_id = 1),'Outra despesa',(SELECT id FROM tipo_subgrupo WHERE nome = 'variável'));
